name: Deploy

on:
  push:
    branches:
      - gh-actions-deploy

jobs:
  predeploy_and_deploy:
    name: Predeploy and deploy build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm install
      run: npm install
    - name: predeploy
      run: npm run predeploy
    - name: deploy
      run: npm run deploy
