name: Deploy
on:
  workflow_run:
    workflows: ["Build, Test, Lint"]
    branches: [master]
    types: [completed]

jobs:
  predeploy_and_deploy:
    name: Predeploy and deploy build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm install
      run: npm install
    - name: predeploy
      run: npm run predeploy
    - name: deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build
