name: Master - build, test, lint, deploy
on:
  push:
    branches:
      - master

jobs:
  build_and_test:
    name: Build and Test on node ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: npm install
    - name: npm build
      run: npm run build --if-present
    - name: npm test
      run: npm run test-ci

  linting:
    name: Run linting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: npm install
      run: npm install
    - name: Run eslint
      run: npm run lint

  predeploy_and_deploy:
    name: Predeploy and deploy build
    needs: [build_and_test, linting]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: predeploy
      run: npm run predeploy
    - name: deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build
